24 sprint 2 view single student information
DeltaO3/UWAttend---3200_27 pull request #116
Opened 2024-09-23 02:34 UTC by ipr17

Ok so key things I changed (all on /student):

Added 'Remove Student' button, which deletes the attendance record for that student. 
Added the ability to edit sign in/out times.
Added ability to sign out individual students (but only from student page - home page coming soon).
Now pressing 'Save Changes' will cause updates to all fields where data was given.

2024-09-23 03:24 UTC, DeltaO3 requested changes
looks great! code mostly looks ok:

Some issues tho:
You arent checking nonetype, causing a crash (this is an edge case but still crashes)
![image](https://github.com/user-attachments/assets/9be1f296-ca70-447b-9116-9f3459d0114a)
Error message on page could potentially display what the issue was? currently just gives "error updating student details"

Not sure why  sign in includes seconds but sign out doesnt? can this be fixed?
![image](https://github.com/user-attachments/assets/2f988e0d-9c9e-4f75-8900-dc1bed5a4d72)
Seems to be causing issues - cant sign students out, keeps printing that its an invalid format?

Displays correctly if i sign all students out first

2024-09-26 03:24 UTC, ipr17 commented
@DeltaO3 I cannot replicate the case where the seconds do not show up for sign out time, do you remember how you came across this? I also have not gotten any errors about signing students out, so I don't know how to debug that either.

2024-09-26 07:19 UTC, DeltaO3 approved these changes
LGTM!

2024-09-26 08:40 UTC, ipr17 commented
make it so that if a student removes or adds consent, it changes their student value

2024-09-27 03:40 UTC, livvy10 approved these changes
requested changes will be done on a separate issue

2024-09-28 02:20 UTC, DeltaO3 commented on app/routes.py
>  # STUDENT - /student/
Should this not have login required?

2024-09-28 06:31 UTC, livvy10 commented
are we happy with it as a stringfield? I like it more as textarea as it has more space and you can do returns and things, but not a big issue at all
also it's coming up with None as the comment if nothing is set, but i think it should be blank
either I think we could initialise all attendance entries with "" as comment

2024-09-28 09:38 UTC, livvy10 approved these changes

2024-09-30 01:59 UTC, merged