131 sprint 3 frontend overhaul
DeltaO3/UWAttend---3200_27 pull request #142
Opened 2024-10-02 08:08 UTC by DeltaO3

The full PR.

I am not 100% happy with everything here, but I think if I try any longer I will end up getting myself to 100 hours with nothing of note pushed in. Happy for the most part.

Key things:
Support for browser light/dark via css. 
Support for css variables to allow ease of colour customisation (all at the top of the css file, just change the colours)
All pages have had some degree of frontend overhaul, except for unit config as it does not exist yet (??? please theres one week)
(Hopefully) everything is overhauled to some degree to use these css variables so we shouldn't need to worry about it in the future if we change things, it should be mostly universal (only thing i can think of is some of the color-mix() calls are somewhat arbitrary and may need change depending on colours).

Login page no longer displays navbar.
Error alerts dismiss themselves after 3 seconds (easy to change, its in main.js)
Home page now has scrolling for the table if it gets big - uses js to calculate how large that particular element needs to be in order to utilise overflow. Jquery event fires on load, screen size change, or alert dismissal.
Home page suggestions no longer move the page
Student page revamp to display nicer on desktop and mobile (hopefully)
Session page redo to not take up an ungodly amount of space
Similar with admin page
Addunit page redo (shudders), utilising jinja macros to keep the html file as clean as possible. Now displays in multiple columns or partial columns on desktop / mobile respectively, to attempt to improve readability.

Probably a bunch of minor things I have forgotten.

I have NOT touched the multi-select much as it confuses me as to its existence (and causes pain to try and design around).
I have NOT made the session names and comment suggestions have proper input types, it is still | seperated. I figure this will take even more time and everything still functions and is probably well beyond the scope of what has become a very large issue.
I am not *quite* happy with the addunit page, but I'm happier than the way it was before. Its also much easier to edit the format and such thanks to the macro.

https://drive.google.com/file/d/1f3UvnCZsnE8ul07cCY81Y_TqlpUwlmtO/view?usp=sharing

Google drive link containing a video running through the site in dark mode. (Too big to upload to github).

Functionality shouldn't have broken, but defs double check!

2024-10-02 11:51 UTC, ipr17 requested changes
Looks great! I tried for a while and didn't manage to find any changed functionality, which is great. Love the new look of all the pages, and super cool that it works for light and dark mode with the browser! Really, super great, love it. I think it's probably good if someone else takes a look too, just because this PR spans basically the whole app and there are a lot of pages that I haven't touched before. 
Just put request changes because of that one comment that I left, but happy to change if we have already made a call on that and I missed that conversation.

2024-10-02 11:51 UTC, ipr17 commented on app/templates/admin.html
> +        <h2 class="mb-3">Add a Coordinator</h2>
So could definitely be me misunderstanding, so super happy to drop this if so as this is my only problem with this PR. 
Before, the admin page had it so when a user was filling out the form to add someone to the database, they would select between admin, coordinator, and facilitator. This doesn't exist anymore here. I understand why a user wouldn't need to be able to add a facilitator from here, but do we want to be able to add an admin user? Just because if Adrian was to leave or wanted another person to help running the webapp, he would need to be able to add new admin accounts. Just a thought.

2024-10-03 02:40 UTC, DeltaO3 commented on app/templates/admin.html
> +        <h2 class="mb-3">Add a Coordinator</h2>
Happy to add this but I dont believe it was there before? might be missing something

2024-10-03 02:52 UTC, DeltaO3 commented on app/templates/admin.html
> +        <h2 class="mb-3">Add a Coordinator</h2>
Nope! i totally deleted the field accidentally. Added it
![image](https://github.com/user-attachments/assets/77adfa7f-1d55-48f6-b358-e60dcb3364f0)

2024-10-03 03:20 UTC, ipr17 approved these changes

2024-10-03 09:24 UTC, livvy10 reviewed
omg delta this looks amazing, you are a bloody frontend legend

couldn't find any issues with functionality breaking so think it all works fine

just one thing - I remember him saying he wanted more details in the add unit page e.g. specifying that the unit will not appear on facilitators' session config pages if it is not within the dates. It might be good to add this now?

2024-10-03 13:52 UTC, DeltaO3 commented
I can add that in the morning if wanted, but might just add it seperately

2024-10-03 13:54 UTC, merged