44 sprint 2 download template for student csv
DeltaO3/UWAttend---3200_27 pull request #150
Opened 2024-10-04 01:50 UTC by ipr17

Added two buttons on the "add unit" page, so that a user can download a template for the student or facilitator csv. it's being served with flask's send from directory. will need to test this in the production environment eventually, as I don't know if it will force a different level of security that won't like how I'm prompting the download. 
If we want to change the templates or the sample data or anything, we just change the files in static/files later

2024-10-04 02:25 UTC, DeltaO3 approved these changes
I edited the formatting a bit but otherwise LGTM!

2024-10-04 03:43 UTC, Ay1tsMe requested changes
![image](https://github.com/user-attachments/assets/9c8e13cb-95fd-4dda-9525-b5f90a876a8e)

Buttons are misaligned. Happy to merge once fixed

2024-10-05 06:12 UTC, DeltaO3 commented
@Ay1tsMe Waiting for approval, think i fixed the formatting yesterday?

2024-10-06 13:20 UTC, Ay1tsMe approved these changes

2024-10-07 03:53 UTC, merged