121 sprint 3 add frontend unit table and edit unit page
DeltaO3/UWAttend---3200_27 pull request #158
Opened 2024-10-05 07:00 UTC by Jimbos21

What has been added:
- Updateunit page and functionality
- A table showing all units user is managing which can be clicked on to lead to that units update unit page
- Some new functions to help facilitate the above

What still needs to be done:
-Updating the front end of updateunit.html to match the front end overhaul
- Maybe small front end changes to unit.html, looks good imo but change if it feels necessary.

2024-10-05 07:45 UTC, livvy10 commented on app/forms.py
> +
The way session occurrence is set by the coordinator has been changed to use only Hours or Morning/Afternoon (see the more recent add unit page)

2024-10-05 07:54 UTC, livvy10 requested changes
Looks pretty good! From my testing it appears to successfully update the unit (which is needed for start and end date so that's great)

2024-10-05 07:54 UTC, livvy10 commented on app/forms.py
> +    )
The way session occurrence is set by the coordinator has been changed to Hours or Morning/Afternoon select field, see the new add unit page

2024-10-05 07:54 UTC, livvy10 commented on app/routes.py
> +        )
I don't think admins should have access to everyone's units in the unit config page. Adrian will be an admin, on his unit config page he should just have his own units imo. 
If we more time it could be an idea to add all units on the admin page for admins to be able to see or change, but I don't think we will have time for this (even though it would be a lot of copy and paste)

2024-10-05 07:54 UTC, livvy10 commented on app/routes.py
> +
If new facilitator and student files are submitted, are the relevant details actually updated? e.g. new facilitators added as users if not already and then added to the facilitator_unit association table

2024-10-09 07:18 UTC, DeltaO3 commented
Some quikc notes:
Using 2 forms seems really redundant and adds more bloat to some already bloated files. Either look into inheritance or maybe you can just use the same form without rendering the facilitator upload parts? it may dislike you tho.
How do we want to display students/facilitators? we don't want this to just be a re upload do we? we'll need to edit students/facilitators/delete/add which is like just creating the entire home page again...

2024-10-10 05:59 UTC, DeltaO3 commented
Vastly improved PR, almost done, with some small issues:
How are we handling updating students and facilitators? CSV upload or seperate page?

2024-10-10 08:06 UTC, DeltaO3 commented
Students can now be added and deleted. There is no validation of student duplicates yet ( i dont think so at least), but that should be easy enough. 
To whoever adds facilitators - add another button in the conditional, and then render the same template but use conditionals to change what is displayed.
I will finish this maybe tonight or in the morning if no one else does but I'd rather not.

2024-10-12 03:52 UTC, ipr17 approved these changes
Wow that is a huge PR. Looks great. I tried to mess around with other units that weren't associated with a certain coordinator but I couldn't find any way to do that (I am no hacker though so maybe someone else should try as well?)
The only thing that I noticed in terms of functionality that could be changed is as far as I can tell, there is no way to remove session names or comment suggestions. As in, you can add one or two and immediately remove them, but if you are editing a unit you can't remove one that you made when you initially set up the unit. This seems pretty minor though, so I am happy for this to go through anyway.

2024-10-12 03:59 UTC, DeltaO3 commented
I can remove ones i made when initially setting up the unit? Does it not work in the backend somehow?

2024-10-12 04:44 UTC, livvy10 approved these changes
All works for me!
checked trying to access other coordinator's units and that redirects and errors as intended

2024-10-12 05:05 UTC, merged