flask routing upload
DeltaO3/UWAttend---3200_27 pull request #34
Opened 2024-08-17 09:37 UTC by ozzy1323232

replace render_template with genuine htmls

2024-08-17 14:02 UTC, Ay1tsMe commented
I think there are a couple problems that need to be addressed.

Firstly, your code should be refactored into the existing `routes.py` instead of being a separate file called `Zac_Morris_ROUTING.py`. I think having multiple files for routes would cause conflicts.

And secondly, the initialisation code doesn't need to be there because it's already being initialised in `__init__.py`. 

So what I would do is remove this as it's already present in `__init__.py`:
```
import flask



app = flask.Flask(__name__)

```
Then move all the routes you defined in `Zac_Morris_ROUTING.py` into `routes.py`. That way all the routes are in one location.

2024-08-17 14:13 UTC, ozzy1323232 commented
> I think there are a couple problems that need to be addressed.
> 
> Firstly, your code should be refactored into the existing `routes.py` instead of being a separate file called `Zac_Morris_ROUTING.py`. I think having multiple files for routes would cause conflicts.
> 
> And secondly, the initialisation code doesn't need to be there because it's already being initialised in `__init__.py`.
> 
> So what I would do is remove this as it's already present in `__init__.py`:
> 
> ```
> import flask
> 
> 
> 
> app = flask.Flask(__name__)
> ```
> 
> Then move all the routes you defined in `Zac_Morris_ROUTING.py` into `routes.py`. That way all the routes are in one location.

OK, sorry i wasnt aware that those programs were already built........

2024-08-18 02:12 UTC, DeltaO3 requested changes
In addition to what has already been said (please just put the routes in the existing routes.py file, theres already an example there) , there are *way* too many empty lines. Generally there should be one empty line between each function.

2024-08-18 05:26 UTC, DeltaO3 requested changes
Overall looking fine, still a few minor things to change

2024-08-18 05:26 UTC, DeltaO3 commented on app/routes.py
> +app.run(port=5958)
this is unnecessary

2024-08-18 05:26 UTC, DeltaO3 commented on app/routes.py
> +@app.route('/home', methods=['GET'])
home should include the nameless / route as well

2024-08-18 05:26 UTC, DeltaO3 commented on app/routes.py
> +    return flask.render_template('1.html')
Can you perhaps rename each html file to their route name? eg home.html, session.html etc. Make it quicker to work on these once all merged into our own repos

2024-08-18 05:26 UTC, DeltaO3 commented on app/routes.py
> +# STUDENT - /student/
I'm of the opinion that this shouldn't be a route - should be checked via user login credentials (implemented in another issue) - not 100% sure here though. We can discuss this, and potentially leave it as is for now.

2024-08-18 05:26 UTC, DeltaO3 commented on app/routes.py
> +
Gap of spaces is still unnecessary.

2024-08-18 05:27 UTC, ozzy1323232 commented on app/routes.py
> +
?? it looks cleaner?

2024-08-18 05:28 UTC, ozzy1323232 commented on app/routes.py
> +app.run(port=5958)
why

2024-08-18 05:34 UTC, DeltaO3 commented on app/routes.py
> +app.run(port=5958)
the app is ran through the flask readme, and defaults to port 5000. you can change this port with a command in the command line. Read the readme (flask run -p "port_number")

2024-08-18 05:34 UTC, DeltaO3 commented on app/routes.py
> +
I'll leave this to group consensus

2024-08-18 05:37 UTC, ozzy1323232 commented on app/routes.py
> +app.run(port=5958)
ok just updated

2024-08-18 05:38 UTC, DeltaO3 requested changes
We dont want the same function called twice when two routes link the same page.
Still disagree about the line breaks, think we as a group should have a basic stylistic consensus written somewhere, will cede the point if others don't mind

2024-08-18 05:38 UTC, DeltaO3 commented on app/routes.py
> +def home():
You can define both app routes above a single function instead of having two functions :
```
@app.route('/', methods=['GET'])
@app.route('/index', methods=['GET'])
def home():
```

2024-08-18 05:44 UTC, DeltaO3 approved these changes
Good enough for now , approving, but another reviewer please look and comment

We should decide on styling standards for spaces however, as I don't like multi line line breaks personally. (meeting agenda point?)
Also still unsure if we want student to be its own route - Someone please comment on this before blindly approving.

2024-08-18 06:56 UTC, Ay1tsMe commented
If I try running this branch with a sample `home.html`, I get the following error:
```
  File "/home/adamw/Sync/SEM22024/CITS3200 Professional Computing/Project/UWAttend/app/routes.py", line 11, in home
    return flask.render_template('home.html')
           ^^^^^
NameError: name 'flask' is not defined
```

This is because `flask` hasn't been imported from the file. Only the `render_template` has been imported. So to fix this, either the name `flask` needs to be removed from every `render_template` return statement or the import statement needs to be changed. So the correct examples would be either:
```py
from flask import render_template
from app import app

@app.route('/home', methods=['GET'])
def home():
    return render_template('home.html')  # This is the correct usage
```
or this:
```py
import flask # This is the correct usage
from app import app

@app.route('/', methods=['GET'])
def home():
    return flask.render_template('home.html')
```

To address Delta's questions:

I prefer the file without extra spaces between route definitions. It keeps the code more compact and easier to read. We can leave it for now but we should change it in the future.

I suggest we keep the `/student` route for now. It might be useful if we decide to expand use functionality later on. If we don't need it, we can always remove it in the future without much hassle.

I also noticed that this merge request has 17 messages for a relatively small change. While it's great that everyone is contributing, we should aim to keep our comments more concise and focused to avoid bloating the conversation.

2024-08-18 07:00 UTC, ozzy1323232 commented
i just updated it

2024-08-18 12:04 UTC, Ay1tsMe approved these changes

2024-08-19 02:24 UTC, DeltaO3 approved these changes
LGTM, approved. (Reason for many comments is becuase reviewing code adds these, comments below code to point out where your talking about is how I am used to it, at least.)

2024-08-19 02:26 UTC, merged