Sprint2 - Session Configuration Menu
DeltaO3/UWAttend---3200_27 pull request #35
Opened 2024-08-18 14:17 UTC by Ay1tsMe

Ready to merge. Web-page is accessible through `/session` so test it out!!!!

I added the `Semester` input field because that's what he had in the demo. We could probably use the current date to work out which semester it is but leave it for now. 

Also there is a clock that displays the `Current Time` for the user. Not sure if this is necessary but their were discussions about whether we want this instead of "Morning" or "Afternoon" options.

2024-08-19 02:39 UTC, livvy10 commented
Looks really good so far, I liked your code style, it's written very clearly. I accessed the session page as you said and filled in the form successfully!
Considering this is for configuring a session by facilitators, I believe Adrian doesn't want them to have a semester choice as that will already known by the db.
I think instead of having text boxes for inputs where an error is shown if it is invalid, there should just be selection boxes and you have to pick from one of the valid units. (Although keep html validation in the unlikely instance they muck around with the actual html and try to submit an invalid input - I think that's a thing??)
Also I think this should be done in a form with forms.py - not sure if this was something to change to at a later stage though.

2024-08-19 02:44 UTC, DeltaO3 requested changes
Overall looks pretty good, skeleton functionality is great!
Main thing is the client said he didn't want semester, spent a while going over that point last meeting. I think we should just not include it (for now) so that if we show him this next meeting he doesn't think we didnt listen to him.

Minor comments below on things i'd change but am fine without for now, due to the skeleton nature of the html file.

2024-08-19 02:44 UTC, DeltaO3 commented on app/templates/base.html
> +    <script src="{{ url_for('static', filename='styles/main.css') }}"></script>
Pretty sure we want to use <link> to include our css, and CSS should be in the head, after the bootstrap link.
The script included on line 14 is a CDN for jquery (and thus a script). not 100% certian here, but fairly certain.

2024-08-19 02:44 UTC, DeltaO3 commented on app/templates/session.html
> +    <!-- Buttons -->
Buttons should include the class btn, but i understand you've just gone for the html/js skeleton here, so its fine for now.

2024-08-19 14:39 UTC, Ay1tsMe commented
Fixed all the issues brought up. Should be good to go

2024-08-20 02:06 UTC, DeltaO3 approved these changes
LGTM! Just be wary when updating from main - you have some files that were manually merged from a branch but are now merged, so you aren't up to date. Hopefully git is smart.

2024-08-22 13:04 UTC, livvy10 approved these changes
All the new changes look great!
In the future I think the unit selected should determine which sessions can be selected from - but this is beyond the scope of this issue.

2024-08-22 13:06 UTC, merged