added single student view information page and basic flask route
DeltaO3/UWAttend---3200_27 pull request #39
Opened 2024-08-22 08:52 UTC by ipr17

i didn't make it connected to the home page, so you have to type /student at the end of the url for now... figured that was outside the scope of this issue

2024-08-22 09:17 UTC, DeltaO3 requested changes
Overall, looks ok. 100% should be redirect, not render, and minor comment about the buttons. I don't think this is done (should likely just be a modal popup, not its own page? imo) but am happy to let this go through, and make a seperate isssue to improve its display and such. We can talk about in meeting.

2024-08-22 09:17 UTC, DeltaO3 commented on app/routes.py
> +from flask import request, render_template
not 100% sure, but since we're just importing flask entirely (don't know if that's good practice but it's what we're doing), this is probably un-necessary?

2024-08-22 09:17 UTC, DeltaO3 commented on app/routes.py
> +    return render_template('home.html')
This should be redirect to home, not render template.

2024-08-22 09:17 UTC, DeltaO3 commented on app/templates/student.html
> +        <!-- Action Buttons -->
These should almost definitely be the other way around, by convention. Formatting is also off (buttons should have a gap between themselves and the edge), but I don't mind too much for this issue.

2024-08-22 09:22 UTC, ipr17 commented on app/routes.py
> +    return render_template('home.html')
yeah i'm happy to change that, didn't really consider it tbh

2024-08-24 02:12 UTC, DeltaO3 approved these changes
LGTM!
I had a brain moment and realised that yeah, importing flask fully does look a bit uglier. Maybe something to discuss at some point - fsr i thought you could just use redirect from a flask import - I wasn't thinking.

2024-08-24 14:14 UTC, Ay1tsMe approved these changes

2024-08-24 14:14 UTC, merged