26 sprint 2 database design models
DeltaO3/UWAttend---3200_27 pull request #47
Opened 2024-08-24 05:25 UTC by ozzy1323232

i added the database (it completly empty except for the password login acounts(login_data table) ) so config.py will work without errors

2024-08-24 07:28 UTC, DeltaO3 requested changes
Schema looks alright for now, a few things:
1. The database should be defined in the models  e.g. foreign keys and relationships should be defined in sqlalchemy.
2. I believe you have installed new dependencies (sqlalchemy) - you should ```pip freeze > requirements.txt``` to add the dependencies to the requirements.txt file.
3. This one im not 100% sure about, but should be pushing the db to the github? My previous project did end up having a database in the repo, but can you not run ```flask db init``` to initialise the database? I may be wrong here, someone else definitely check. We will likely need it in our final build once theres no more changes to the models (and thus schema)

2024-08-24 07:28 UTC, DeltaO3 commented on app/models.py
> +    SessionId = db.Column(db.Integer)                        # this is a foreign key defined in the database itself
should add a  db.ForeignKey() to the definition here then, I believe.

2024-08-24 07:28 UTC, DeltaO3 commented on app/models.py
> +    UserId = db.Column(db.Text)                # this is a foreign key defined in the database itself
Again, should be defined in model as a foreign key then?

2024-08-25 01:08 UTC, ipr17 requested changes

2024-08-25 01:08 UTC, ipr17 commented on app/models.py
> +    SessionId = db.Column(db.Integer)                        # this is a foreign key defined in the database itself
Small thing: PreferedName should be PreferredName. Not a big deal, but we don't want to miss this. Also I think the professor said he wants the default value of consent to be None before the student has given an answer about their consent, and then it should be updated to Yes or No.

2024-08-25 03:02 UTC, ozzy1323232 commented on app/models.py
> +    UserId = db.Column(db.Text)                # this is a foreign key defined in the database itself
will implement that later because its not really needed yet and will cause sqlite errors at the moment, when the database functions are implemented then its safe to put integrity guards and foreign keys in the database schema

2024-08-25 03:03 UTC, ozzy1323232 commented on app/models.py
> +    SessionId = db.Column(db.Integer)                        # this is a foreign key defined in the database itself
with foreign keys they play a part in integrity checks which should be done after the functionality is written. they are not neccessary yet

2024-08-25 09:07 UTC, livvy10 commented
Just some further comments on what Delta said:

> 3. This one im not 100% sure about, but should we be pushing the db to the github? My previous project did end up having a database in the repo, but can you not run `flask db init` to initialise the database? I may be wrong here, someone else definitely check. We will likely need it in our final build once theres no more changes to the models (and thus schema).
>    A tiny bit more research and I do think some db file needs to be in the repo, but should we add it to gitignore?

I tried flask db init and it didn't work (after I installed necessary stuff). Potentially more needs to be added to UWAttend.py (at least what I can gather from comparison between this and my web dev project). But tbh honest I don't really understand what we did so maybe someone else who knows dbs better than me can also have a look. 

And yes I agree, I don't think the db should be in the repo (but maybe a small one for testing is fine)

2024-08-25 09:13 UTC, ozzy1323232 commented
> I tried flask db init and it didn't work (after I installed necessary stuff). Potentially more needs to be added to UWAttend.py (at least what I can gather from comparison between this and my web dev project). But tbh honest I don't really understand what we did so maybe someone else who knows dbs better than me can also have a look.

So its a bit confusing, i did some research on whether we should literally 'create' the DB in python OR create it using slqite and upload. basically we shouldnt do it in python because its only going to be 'created' once and then after that it ignores it. There are issues as we need an already built database with the password / admin accounts. if we create the databse in python code it wont have any of that data. So i have uploaded a DB with the necessary data we need.

2024-08-25 09:23 UTC, livvy10 commented
I think this is a really good start and translates the current system into one using sqlalchemy and models. While I don't agree with some of the fields, I'm ok with us updating it later when we have Adrian's current data so we can have a look at what data is being stored and how, and make the necessary changes then.

Also I know this feels unimportant, but I would recommend having different names, none should have "_data". I think these should be thought of as similar to classes, so for example, instead of login_data, the name User would be better.

2024-08-25 09:25 UTC, ozzy1323232 commented
> I think this is a really good start and translates the current system into one using sqlalchemy and models. While I don't agree with some of the fields, I'm ok with us updating it later when we have Adrian's current data so we can have a look at what data is being stored and how, and make the necessary changes then.
> 
> Also I know this feels unimportant, but I would recommend having different names, none should have "_data". I think these should be thought of as similar to classes, so for example, instead of login_data, the name User would be better.

sorry the reason i used _data was because there were naming confilcst in the imported modules....... User() and Login() were already taken and giving erros, so i had to rename tables to login_data. we can change this though.

2024-08-25 09:33 UTC, livvy10 commented
> > I tried flask db init and it didn't work (after I installed necessary stuff). Potentially more needs to be added to UWAttend.py (at least what I can gather from comparison between this and my web dev project). But tbh honest I don't really understand what we did so maybe someone else who knows dbs better than me can also have a look.
> 
> So its a bit confusing, i did some research on whether we should literally 'create' the DB in python OR create it using slqite and upload. basically we shouldnt do it in python because its only going to be 'created' once and then after that it ignores it. There are issues as we need an already built database with the password / admin accounts. if we create the databse in python code it wont have any of that data. So i have uploaded a DB with the necessary data we need.

The way we did it in web dev is with flask db init (which intialises a db based on the given models). This is only done once (although we would each do it and have our own db whilst coding as usually you shouldn't push db to the repo). You can also just insert data manually if needed with some extension on github (I think sqlite or sqlalchemy??) which lets you view the database and do CRUD operations, e.g. if we need to insert certain users including admin account. So I think we can still do it using flask db init and migrations (although keep in mind this is just what we did in web dev which worked nicely, and I don't know what methods are considered better - someone else who knows more can hopefully let us know).

2024-08-25 10:50 UTC, livvy10 reviewed
I'm not sure the changes have been properly committed?? It's not showing up for me and still says PreferedName - not sure if I am doing something wrong tho

2024-08-26 02:21 UTC, DeltaO3 commented
From Adam:
>Okay just to add my two cents. Probs a bit late to comment but whatever. We should be initialising the sqlalchemy database programmatically. Everyone on the team should be building there own database file using predefined code. I don't know if we have a models.py file but we should be initialising the database environment with models using models.py . It's bad practice for there to be a .db file that everyone shares. Need to have a look at how flask works but just thinking about it with flask removed from the picture, the code should be creating and organising the database, not the end user.

2024-08-27 14:53 UTC, livvy10 requested changes
I thought leaving discuss my thoughts about the schema until after we had merged would be fine so we had an initial thing to work with, but after Delta mentioning us making the schema as correct as possible (as migrations with 6 could get icky) and to include foreign keys and relationships I thought I better give my feedback now.

Firstly, I believe we are planning to implement the app without Callista (and will try to work with it later if possible). So we need to store student information, as given by the unit coordinator at the beginning of the semester when they coordinate the unit (user flow diagram 2c). Also we need to store the rest of the unit configuration details.

I think having 5 main tables will capture all this: User, Unit, Student, Session and Attendance. Where Student stores student info for a given unit (as given by unit coordinator) and Unit stores the unit configuration details. (User is just your login_data, and the others are the same).

I decided it would just be easiest if I put my own thoughts into a draft design, so please see the attached file for my ideas on how we could store the data. It includes relationships to be implemented with flask sqlalchemy's relationship property with back_populates / backref. Using relationships makes working with the python objects (a db tuple/record) super easy, although I'm not sure of the drawbacks of if it makes it too slow. Something to think about.

[Database Schema design.pdf](https://github.com/user-attachments/files/16764031/Database.Schema.design.pdf)

Here are some links I used as I haven't done many-to-many relationships in sqlalchemy before:
https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/
https://medium.com/@beckerjustin3537/creating-a-many-to-many-relationship-with-flask-sqlalchemy-69018d467d36

2024-08-28 02:43 UTC, DeltaO3 commented
At this stage this PR is getting so large, and so much discussion that I think I will table this as a primary point of final decision making during the meeting on friday. We may end up wanting to scrap this and make a new issue for this and start again from scratch with a definitive idea of how we are doing it. I agree with olivia's proposals above for the most part - callista integration will likely be tricky, and is a sprint 3 goal.

2024-09-05 02:57 UTC, closed without merging