21 sprint 2 admin configuration
DeltaO3/UWAttend---3200_27 pull request #60
Opened 2024-08-28 16:35 UTC by Jimbos21

Have created the template and form needed for the add unit page. Need an add session page, admin page and update unit page.

2024-08-29 04:48 UTC, livvy10 requested changes
Looks really good so far and well-written!

I think there are a couple more fields that are needed.
- session names. this is where they can put in any number of session names (Strings) (e.g. Pipeworks, CAD). The way I envisioned this is a place for them to type, then they can press add and it adds the session name just underneath, then they can type in another one to add. I don't know exactly how to do this and believe it will require some funky javascript, so perhaps for now, just use a StringField (and they can just add a comma-separated list of session names).
- session occurrences. this is where they can select from pre-defined values e.g. Morning, Afternoon, 10AM (so selectField) 
- use barcode reader (boolean)
- add assessment check (boolean)
- add comments (boolean)
- comment suggestions (would ideally be similar to session names, so for now Stringfield I think is fine for them to submit comma-separated suggestions for comments)

2024-08-29 04:51 UTC, livvy10 commented on app/forms.py
> +    #Need to add custom validators to check if files uploaded end in csv
Windows has strict name endings but I think other OSs don't care, so I'm not sure we would need this check

2024-08-29 04:52 UTC, livvy10 commented on app/routes.py
> +
Maybe for debugging you can print each of these out, just so when testing we can see that the form works as intended - just an idea!

2024-08-29 06:32 UTC, DeltaO3 requested changes
Overall looks pretty good (Espeically for a first time using most of the tech and github from what im gathering!) - some minor questions with the css file (dunno whats happening there), and the formatting could use work but thats universal across front end (a sprint 3 goal). Looks pretty good aside from what has already been mentioned!

2024-08-29 06:32 UTC, DeltaO3 commented on app/static/styles/main.css
> +}
Any reason for the random stray closing bracket? may be a remnant of something earlier?

2024-08-29 06:32 UTC, DeltaO3 commented on app/static/styles/main.css
> +
similarly with this random space - you arent changing the file elsewhere - not a big deal at all! but pointing it out because i dont see any changes to this file

2024-08-29 06:35 UTC, DeltaO3 commented
A question - I'm not 100% sure, is this to be accessed via the admin route? or is it part of session, or is it its own page?

2024-08-29 06:49 UTC, livvy10 commented
> A question - I'm not 100% sure, is this to be accessed via the admin route? or is it part of session, or is it its own page?

So I believe eventually (as in probs next week) the /admin route will instead be for an admin page with various buttons, including a button called 'configure new unit', which when clicked will take you to this add new unit page which James has just done. However, this was only included in draft 3 of the user flow diagrams,, so when we made the initial issue for James to work on, we thought the /admin route was going to be the add new unit page.

So James and I discussed it and came to the conclusion that he could just do the issue as intended for now (draft 3 hadn't even been merged yet), and then when we get feedback from Adrian about user flow diagram draft 3 we could make the changes later.

Although if you reckon we should change it now it shouldn't be too hard right? Just changing the name of the html file to add_new_unit.html and making a separate route for it /add_new_unit

2024-08-30 00:45 UTC, DeltaO3 commented
Can be done in this PR or a later one, I dont mind

2024-09-05 02:57 UTC, DeltaO3 commented
PR is stale, is anyone still working on this?

2024-09-08 01:21 UTC, DeltaO3 approved these changes
LGTM!

2024-09-08 03:16 UTC, livvy10 approved these changes
All looks good, all changes implemented as requested.
We should make a point to discuss which data should be required or not in the add unit (considering that when we add the ability to edit the unit that may change our opinions). But not necessary for now

2024-09-08 03:18 UTC, livvy10 commented
We also need someone to change the routing to be correct (as this should be add unit, and should be accessed through a button on the admin page i.e. /admin route) but I think this was a separate issue

2024-09-08 03:19 UTC, merged