Added the database functions
DeltaO3/UWAttend---3200_27 pull request #67
Opened 2024-09-03 04:52 UTC by ozzy1323232

Documentation listed on discord

- will need deletion soon
- Needs feedback on what extra functions are needed. At the moment only table Attendance can be updated

2024-09-04 07:11 UTC, DeltaO3 requested changes
Overall, looks fine, I think that adding error checking is quite a good idea and one I hadn't thought of.
Some minor issues as pointed out in the below review comments:
get functions should be returning the requested objects, so we can actually use the functions as intended.
Non get functions _probably_ dont need a return statement.
You should attempt to avoid assumptions about the database imo, can you not query for an empty/null entry in signoutTime?

2024-09-04 07:11 UTC, DeltaO3 commented on app/database.py
> +    # and studentID which will confuse the query, for now im hoping the first() will naturally pick the most recent sessionID row with a blank signoutTime column instead of a row from weeks ago
Could you not just add a check for having blank signoutTime to the query then?

2024-09-04 07:11 UTC, DeltaO3 commented on app/database.py
> +    return 0
Dont believe the return statement is necessary here, as well as other times when we are not wanting any data further down the file

2024-09-04 07:11 UTC, DeltaO3 commented on app/database.py
> +    return 0
Should be returning the queried object. in this case, return attendance_records. 

Similarly for most get functions further down

2024-09-04 07:23 UTC, ozzy1323232 commented on app/database.py
> +    return 0
sorry i forgot that, will fix now

2024-09-05 02:29 UTC, DeltaO3 approved these changes
LGTM!

2024-09-05 13:01 UTC, Ay1tsMe approved these changes

2024-09-05 13:02 UTC, merged