Sprint 2 - Export CSV
DeltaO3/UWAttend---3200_27 pull request #69
Opened 2024-09-05 12:59 UTC by Ay1tsMe

Current functionality is to export all tables to csv's and zip them to a `database.zip`. Only tested functionality for the `student` table. Need to test other tables when we have code that populates them

TODO:
- Test other tables that aren't `student`
- Add button to frontend that gives user the database.zip file (waiting for `/admin` page)

2024-09-06 02:16 UTC, DeltaO3 requested changes
Looks great, I feel this and your other issue are similar enough that you could just merge them as one. Again, as my comment in other PR said:
Maybe move student_exists to database.py,
large edit of database file (merge conflict)? makes history hard to track

2024-09-06 03:14 UTC, DeltaO3 commented on app/utilities.py
> +    records = db.session.query(model).all()
also, pretty sure you can use the database function and pass no parameters to get the whole table?

2024-09-06 08:08 UTC, Ay1tsMe commented on app/utilities.py
> +    records = db.session.query(model).all()
Now using `database.py` functions

2024-09-08 01:19 UTC, DeltaO3 approved these changes
LGTM!

2024-09-08 03:36 UTC, merged