29 sprint 2 functional homepage
DeltaO3/UWAttend---3200_27 pull request #77
Opened 2024-09-10 07:42 UTC by ipr17

Sorry about the size of this pull request. I would have preferred to not make it so massive, but because of the late database integration it sort of had to happen that way. Happy to have a discussion with anyone about any of this stuff before it gets merged.

I have not integrated any of my code with the session or unit configuration code, and there is still definitely functionality that needs to be added to the home page, but I figured this is a good start for something to demonstrate to Adrian regarding the home page.

I don't think that Issue 29 (is it?) should be closed with this pull request, for the record, as there is still more functionality to add. 

Also, just to keep things clear, I have tried to comment TODO messages anywhere that I have made an assumption or some sort of simplification that needs to be changed later. (I use the TODO tree extension on VS code so that's what works for me).

2024-09-10 10:31 UTC, DeltaO3 reviewed
cant fully PR this as i cant get it working on my end.
First, theres an import issue - get_perth_time is now in helpers, not utilities.
Then after self populating the database, i cant get past the following error when attempting to add student:
![image](https://github.com/user-attachments/assets/d3545fe7-5759-4467-81f8-543f904156eb)
There should be better error handling for this occurence potentially, i could also be being really stupid with my database ( I hope i am). using the data from sample csv, and that unit.
Could you also potentially explain in the PR what exactly you have added/changed? I can gather it more or less from the code but am not 100% sure.

2024-09-10 10:31 UTC, DeltaO3 commented on app/routes.py
> +            existing_attendance = db.session.query(Attendance).filter_by(studentID=studentID, sessionID=sessionID).first() # TODO should there be a database function for this?
Probably should be for cleanliness imo

2024-09-10 12:10 UTC, ipr17 commented
Yep that GetStudent error that you are having is connected to the simplification of SessionID that I made (i.e. its 1 everywhere)

2024-09-11 01:32 UTC, DeltaO3 requested changes
Managed to get it working fine, looks great! a few issues tho.
- Currently, it is entirely possible to enter a student which simply does not exist, throwing an error.
- I got prompted for consent for a student that had (i believe) in the database already had consent clicked.
- I get prompted for consent when a student already exists in the database
- Currently no way to log students out? happy to leave this as out of scope of this issue its already very large, but make note of it and create a new issue
- Student page seems to not have backend functionality - again, happy to leave as out of scope of this issue, just create an issue.

I like the suggestion thing i imagine that took a lot of time to figure out, and aside from the above it works from my testing. Thanks for this!

2024-09-11 12:26 UTC, Ay1tsMe commented
Can't access the homepage at all due to this error:
```
Traceback (most recent call last):
  File "/home/adamw/Sync/SEM22024/CITS3200 Professional Computing/Project/UWAttend/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adamw/Sync/SEM22024/CITS3200 Professional Computing/Project/UWAttend/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adamw/Sync/SEM22024/CITS3200 Professional Computing/Project/UWAttend/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adamw/Sync/SEM22024/CITS3200 Professional Computing/Project/UWAttend/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adamw/Sync/SEM22024/CITS3200 Professional Computing/Project/UWAttend/app/routes.py", line 17, in home
    current_session = GetSession(sessionID=1)[0]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^
```

2024-09-11 13:09 UTC, ipr17 commented
By the way, to get this working, make sure you have a session with sessionID=1 and all students are assigned to that session

2024-09-12 01:51 UTC, DeltaO3 commented
More details on the crash when invalid student is submitted:

2024-09-12 01:52 UTC, DeltaO3 commented
More details on invalid student crash:
![image](https://github.com/user-attachments/assets/ae807f1a-91d3-4187-8c86-bd0233eda258)
This only happens when trying to submit a student that doesnt exist on the suggestions e.g. any keysmash. This simply should not be possible to submit.

2024-09-12 08:39 UTC, DeltaO3 approved these changes
LGTM!

2024-09-12 09:42 UTC, merged