Adding test DB initialisation script
DeltaO3/UWAttend---3200_27 pull request #90
Opened 2024-09-15 05:09 UTC by DeltaO3

Instructions to run the script included at the bottom of the readme. Simple script to initialise database with test data

2024-09-15 05:32 UTC, ipr17 approved these changes

2024-09-15 05:32 UTC, ipr17 commented on README.md
> +python - m app.testdb
tiny tiny thing, there is a typo on this line. I mean its obvious what you mean (-m not - m) but might be best to ensure the documentation is correct. The rest looks great though :)

2024-09-15 05:35 UTC, DeltaO3 commented on README.md
> +python - m app.testdb
lmao how did i miss this, good catch

2024-09-15 14:35 UTC, livvy10 requested changes
Mine crashed... I think the issue is potentially just a typo for the add unit to facilitator 44456666 but there is no user with that uwaID, instead it is probably meant to be the user  44446666? As far as I can tell I don't think addunittofacilitator automatically makes a user if they don't already exist

 File "/home/olivia/UWAttend---3200_27/app/testdb.py", line 21, in <module>
    AddUnitToFacilitator(44456666, unit1)
  File "/home/olivia/UWAttend---3200_27/app/database.py", line 161, in AddUnitToFacilitator
    user.unitsFacilitate.append(unit)
AttributeError: 'NoneType' object has no attribute 'unitsFacilitate'

2024-09-16 01:40 UTC, DeltaO3 commented
Should be fixed, dunno how 2 typos passed through this

2024-09-16 02:16 UTC, livvy10 approved these changes
works for me!

2024-09-16 02:16 UTC, merged